### ISSUE TITLE
Implement selector combining optimization

### ISSUE THREAD

**Issue by daira** [zcash/halo2#116]
There's an optimization we can do after floor planning: if two or more selectors are never used on the same row, then they can be combined into one selector, subject to max degree limitations.

For example, if we have polynomial constraints q<sub>A</sub> · p<sub>A</sub>(...) = 0 and q<sub>B</sub> · p<sub>B</sub>(...) = 0, where q<sub>A</sub> and q<sub>B</sub> are boolean selectors that are never used together, then we can transform that into q<sub>C</sub> · ((q<sub>C</sub> - 2) · p<sub>A</sub>(...) + (q<sub>C</sub> - 1) · p<sub>B</sub>(...)) = 0, where q<sub>C</sub> = 1 if q<sub>A</sub> is 1;  q<sub>C</sub> = 2 if q<sub>B</sub> is 1;  and q<sub>C</sub> = 0 otherwise.

in order for that to work, we need the optimizer to know which fixed columns are boolean selectors and which regions they are used by.

Alternatively we can do this optimization at the end after synthesis. But I would like to have the information to be able to do it before synthesis if we need to.

**Comment by str4d** [comment]
In PR gardening, @daira said ze would like "non-boolean selectors", that have the two values `[0, non-zero]` rather than `[0, 1]`. These can't be combined arbitrarily; you can combine arbitrary boolean selectors with at most one non-boolean selector.

**Comment by therealyingtong** [comment]
Closed by #347
