### ISSUE TITLE
Allow dumping and reloading a configuration + floor plan

### ISSUE THREAD

**Issue by daira** [zcash/halo2#117]
I think it should be possible to dump an optimized configuration + floor plan in serialized form (e.g. as Rust code that constructs it), and load it back in rather than doing the region sizing / floorplanning / optimization at run time.

For Pollard we can use a single combined core and do such optimizations by hand if they're applicable. But I'd like to make sure that the API is such that they could be done automatically.

**Comment by str4d** [comment]
#547 accidentally duplicated this issue, but there are more details in that issue, so closing this one.
