### ISSUE TITLE
Rename "auxiliary column" to "instance column"

### ISSUE THREAD

**Issue by daira** [zcash/halo2#181]
This was a source of confusion for Kris when reading the [UltraPLONK Arithmetization](https://zcash.github.io/halo2/concepts/arithmetization.html) section in conjunction with the Zcash protocol spec.

In the protocol spec, we use "auxiliary input" for *private* inputs. This follows some papers on proof systems, such as [[BCTV14]](https://eprint.iacr.org/2013/879). In the Halo 2 book and code, we currently use "auxiliary column" for what are usually *public* inputs. Technically, they don't have to be public, but they do have to be part of the instance that is agreed between the prover and verifier.

I suggested that we change this to "instance column", and @sean agreed. Another candidate was "supplemental", but that's a bit too long and hard to shorten.

**Comment by therealyingtong** [comment]
Related to #33 (Fix terminology in code)

**Comment by daira** [comment]
I just closed #103 which was complaining about "auxiliary column" colliding with a third use of "aux" in the description of the lookup argument. If we solve this ticket then we solve that one as well. (I think the remaining clash of "aux" in the lookup argument with "auxiliary input" is harmless.)
