### ISSUE TITLE
Provide abstractions for typed cells

### ISSUE THREAD

**Issue by daira** [zcash/halo2#288]
https://github.com/zcash/orchard/pull/89 implements a `CellValue` abstraction that represents a particular cell containing a field element. But it is error-prone to work with "untyped" field elements. In many cases, we want the circuit implementation to keep track of a high-level type that can be represented as a subset of field elements (for example, a bit, or a bit sequence of fixed length up to the capacity of the field). One possibility is to have a type like `CellValue` (or a trait like `Var`) that has the high-level type as a parameter, where that type is `TryFrom<F>` and `Into<F>` for field type `F`. Then,
* the cell-value returned by a copy constraint, for example, could automatically preserve the high-level type;
* gadget APIs could take typed cell-values as inputs and provide them as outputs.

**Comment by str4d** [comment]
Closed by #383.
