### ISSUE TITLE
MockProver: Track blinding values as "poison"

### ISSUE THREAD

**Issue by str4d** [zcash/halo2#329]
`MockProver` checks circuits manually; in particular, it takes every custom gate, and applies their constraints to every row, to confirm that they pass. For unassigned cells, `MockProver` gives them a default value of zero (to match the behaviour of the regular prover).

#316 introduced blinding rows, which have random, very likely non-zero, values assigned to all cells. `MockProver` was not updated to account for this, and as a result when I tried to update the `orchard` crate to include these changes, we ran into a problem where `MockProver` passed but full verification failed. The cause was that the dummy circuit had a custom constraint forcing all cells to equal zero, which was not gated behind a selector (and thus was applying even to blinding rows).

We _could_ assign random values in `MockProver`, but that could sometimes (though with low-probability) incorrectly pass. @daira suggested that we could instead do something similar to what LLVM does for undefined behaviour: track these as "poison", and propagate the poison where it is used.

Currently, `MockProver` stores cells as `Option<F>`, where `None` represents "unassigned", and gets mapped to zero during gate checks. We should change this to an enum with explicit cases:
- `Unassigned`
  - Maps to zero when checking constraints.
- `Assigned(F)`
- `MultipleAssigned(Vec<F>)`
  - Not necessarily in this issue, but we could subsequently do this for #257.
- `Poison`
  - Propagates when checking constraints except when it is multiplied by zero (since that is how we leave cells unconstrained).

**Comment by daira** [comment]
Can you explain why the Poison and Unassigned cases need to be distinguished (i.e. why they should not both be treated as poison when checking constraints)? I think the semantics should be that cells in *selector* columns default to zero, but accessing any other cell that was not assigned should be an error. I asked this in our tripling but I didn't quite follow the answer.

**Comment by str4d** [comment]
We already have a pass that checks for unassigned cells, and the current behaviour of the main prover is to default init cells to zero, so I'm not inclined to spend the time add this extra complexity to `MockProver` right now. We could maybe do that in future though.
