### ISSUE TITLE
Check probability that Fp/Fq elements can be reinterpreting

### ISSUE THREAD

**Issue by ebfull** [zcash/halo2#34]
Currently, we take field elements from a transcript instantiated over the "other curve" and interpret them as field elements in the "current curve." This is fine for one curve's scalar field but not the other one, because it's smaller. However, it's really close in size so perhaps if the output of the hash is random, there's no way for it to overflow. (Perhaps even when it overflows it doesn't matter?)

**Comment by daira** [comment]
This is fine because the statistical distance between the [0, p) and [0, q) distributions is less than 2<sup>-128</sup>. Actually it is about 2<sup>-164.48</sup> (i.e. (p-q)/p or (p-q)/q, which are roughly the same).
