### ISSUE TITLE
MockProver: Detect when a lookup table doesn't fill the entire circuit

### ISSUE THREAD

**Issue by str4d** [zcash/halo2#348]
When a lookup argument is active, the input side can be set to _any_ row of the table side, including rows beyond the formal bounds of the table. This is a problem because the circuit could have those cells default to any value. In practice they default to zero, which in the case of Sinsemilla would allow the prover to witness the identity in the middle of Sinsemilla usage, which would be a security vulnerability.

We should alter `MockProver` to check that columns involved in the table side of lookup arguments, have been assigned to on every usable row. (The lookup argument itself prevents rows beyond the usable rows from being looked up, which protects the blinding factors.)

**Comment by daira** [comment]
The intention documented in the book was that you could fill the table with copies of a row that is already in the table.

I think the Sinsemilla gadget relies on the ability to look up expressions. That is, if it didn't then it would need an extra advice column for each Sinsemilla instance, so an extra two for the Action circuit.

**Comment by daira** [comment]
I think this was fixed by #354. @str4d?
