### ISSUE TITLE
Double-check that y-coordinate canonicity is preserved in curve implementations

### ISSUE THREAD

**Issue by ebfull** [zcash/halo2#35]

**Comment by daira** [comment]
What do you mean by "y-coordinate canonicity", @ebfull?

**Comment by daira** [comment]
https://zips.z.cash/protocol/protocol.pdf#pallasandvesta
> There is no solution to 0 = x<sup>3</sup> + 5 in either F<sub>q<sub>P</sub></sub> or F<sub>q<sub>V</sub></sub>, and so y cannot be zero. Therefore there is only one valid representation of each point on Pallas and of each point on Vesta; in particular abst<sub>P</sub>(nc) = ⊥ and abst<sub>V</sub>(nc) = ⊥ for nc = I2LEBSP<sub>256<sub>(2<sup>255</sup>). This differs from the corresponding case of abst<sub>J</sub>(nc) for Jubjub, for example.

@ebfull please reopen if that is not what you were talking about.
