### ISSUE TITLE
Smarter parallelization strategy

### ISSUE THREAD

**Issue by ebfull** [zcash/halo2#360]
Right now our parallelization strategy is applied inside of each individual polynomial operation ([see here for example](https://github.com/zcash/halo2/blob/27c4187673a9c6ade13fbdbd4f20955530c22d7f/src/poly.rs#L246)), which means that for every operation between polynomials we end up starting a new threadpool, splitting the polynomial into chunks and then doing the pairwise operation.

This is clearly inefficient in many cases because _everything_ is pairwise -- we should be able to split the polynomials up at a higher layer and then each thread applies all the various operations pairwise on its local section. This avoids overheads from spinning up threads that are quickly thrown away which constitutes a pretty significant portion of the current proving time.

**Comment by str4d** [comment]
Fixing this will likely also fix a performance problem for large circuits where the same rotation is computed multiple times: https://github.com/zcash/halo2/issues/427#issuecomment-991170170
