### ISSUE TITLE
Debug: can MockProver.verify method output more cell value when poly constraint failed?

### ISSUE THREAD

**Issue by DreamWuGit** [zcash/halo2#364]
hi,  Buddies
    Currently we use halo2 lib to write custom gadget, while found it is difficult to debug when constraint fails., comparing to bellman or dusk. because the concrete value can not be retrieve directly for failed expressions.    

Could you have good ways to trouble shooting or make  MockProver.verify output more useful info(values regarding expressions i.e. a - b =0 fails , then print a, b  )?

thanks !

**Comment by daira** [comment]
Do you mean on proving, rather than verification? That information isn't available on verification.

**Comment by DreamWuGit** [comment]
no, I mean use src/dev.rs module 's MockProver.verify() method to dev verification purpose, not generate real proof & verify.

**Comment by str4d** [comment]
This wasn't trivial to do for `halo2` like it was for `bellman`, because you have different kinds of gates (and thus don't immediately know what cells are being used). But it can definitely be done, and we can contain the extra computational work to the failing cases.

**Comment by str4d** [comment]
We can probably repurpose or extend the logic in https://github.com/zcash/halo2/blob/main/src/dev/gates.rs for this.

**Comment by DreamWuGit** [comment]
@str4d  thanks for your reply , currently I add some code to output cells' value in certain row  locally. as the error message will print affected row .  this can help me to trouble shooting to some degree .  also can make pr if you think that make sense.

**Comment by str4d** [comment]
@DreamWuGit could you try #376 and see if it provides what you need?
