### ISSUE TITLE
how to use dev graph 

### ISSUE THREAD

**Issue by DreamWuGit** [zcash/halo2#366]
## Which section of the Halo 2 book were you reading?
dev-graph feature  in https://zcash.github.io/halo2/user/dev-tools.html  

## What was unclear?
there is no code example of illustrating how make one circuit to graph presenting, include which api is used and where used .

## What would help to make it clearer to you?
if there are simple code , from circuit construction to graph dot string or draw to svg directly , so that we can take to use for our own circuit . I think it will be useful for trouble shooting  regarding circuit constraint!

BTW, I see there is simialr test  under "examples/sha256/table16.rs" which title describe "print_sha256_circuit()" , but I can not run it somehow .

Thanks for your updates.

**Comment by str4d** [comment]
`examples/circuit_layout.rs` shows how to use the dev-graph feature. I'll update the book to inline the example, similar to what we do for the simple circuit.
