### ISSUE TITLE
Add support for coefficient blinding factors in poly::commitment

### ISSUE THREAD

**Issue by ebfull** [zcash/halo2#39]
Right now you can only commit to polynomials of degree 2^k - 1, but in the PLONK protocol you'll learn several openings of these polynomials and thus zero-knowledge is broken. In order to fix this we have to commit to a polynomial of slightly larger degree (just enough to compensate for the number of openings) but this is not easy to do with the existing APIs, especially because of the FFTs and the assumptions about the size of the evaluation domains.

This will require changing how the Polynomial structure works (probably forcing it to keep track of the degree of the polynomial) among other things.

**Comment by str4d** [comment]
The way we are planning to add zero-knowledgeness does not depend on this. If it doesn't pan out, we'll reopen this issue.
