### ISSUE TITLE
Classify: Does `Rotation::cur()` represents each row  when create gates ? 

### ISSUE THREAD

**Issue by DreamWuGit** [zcash/halo2#440]
my current understanding is when creating gate,  `VirtualCells` instance constructs and query related advices or others as well ,  the rotation parameter help locates the cell specific position.    
but it is intended to be for relative offset, so what is the base row ?  for now , I tend to interpret `base row`  as each row iteration.  Gating check intuitively loops all rows to ensure constraint , for example, current iteration row is 3 , then `Rotation::cur()` stands for third row and such `Rotation::prev()` means second row and so on.  

let's take https://github.com/zcash/halo2/blob/main/src/dev.rs#L1016L1030 as example :  
this test circuit has 3 columns(a, b, q) and two  usable rows,  one gate to constraint:  
     
```
 meta.create_gate("Equality check", |cells| {   
                    let a = cells.query_advice(a, Rotation::prev());  
                    let b = cells.query_advice(b, Rotation::cur());  
                    let q = cells.query_selector(q);  
                    // If q is enabled, a and b must be assigned to.  
                    vec![q * (a - b)]. 
                });  
```     

when iterate to first row, because `q` is not enable so constraint pass. next iterate to second row ,  `q` is enabled and take `a` value from first row(`Rotation::prev())`) , `b` value from current row(second row) to check if equals .  

please correct me if I am wrong ! welcome your comments here .

**Comment by daira** [comment]
Yes that's correct.

**Comment by DreamWuGit** [comment]
thanks @daira, but `query_selector` does without rotation, I think it always refer to current row selector value.

**Comment by str4d** [comment]
Correct. Selectors are fixed columns that are type-constrained specifically for controlling whether (part of) a constraint is enabled or not. Since all constraints are evaluated on all rows, there's no reason to have selectors be queried at an offset relative to the evaluation row. If someone does happen to require that kind of behavior in their constraints, they can use fixed columns directly.

**Comment by daira** [comment]
Closing; please re-open if you have further related questions @DreamWuGit  🙂
