### ISSUE TITLE
Performance modelling

### ISSUE THREAD

**Issue by daira** [zcash/halo2#47]
Define a parameterized model that can predict the prover and verifier performance of a given Halo 2 circuit, so that I can understand how to optimize circuits. The model needs to be validated against measured performance.

**Comment by str4d** [comment]
Desired UI:
- Write a constraint system using the API we have.
- Input a number of rows.
- Get statistics about how many operations of each type (e.g. FFT of a particular size) it does during proving, how many during verification, and the resulting proof size.

We could collect the data using the [`metrics`](https://crates.io/crates/metrics) crate.
