### ISSUE TITLE
Add a helper for checking `MockProver::verify` results

### ISSUE THREAD

**Issue by str4d** [zcash/halo2#477]
Currently, the way someone checks the result of `MockProver::verify` is with something like:
```rust
assert_eq!(
    prover.verify(),
    Err(vec![VerifyFailure::Lookup {
        lookup_index: 0,
        location: FailureLocation::InRegion {
            region: (2, "Faulty synthesis").into(),
            offset: 1,
        }
    }])
);
```

However, if this fails, all the developer sees is the structural difference between the two, which uses the `Debug` impl of `VerifyFailure`. This is useful if the dev knows what they are doing, but it would be much better if we had a better error renderer, that either leveraged the `Display` impl of `VerifyFailure`, or implemented an even more verbose / instructive error (like `rustc` does 🦀❤️).

What I'm imagining is a `MockProver::verify_valid`, that calls `MockProver::verify` and then if it returns errors, it uses `eprintln!()` to pretty-print an explanation of the errors, and then `panic!()`s to indicate the failure (effectively inlining an `assert_eq!(self.verify(), Ok(()))`).

**Comment by str4d** [comment]
The motivation for this was the error from #478. What the user saw was:
```
  left: `Err([ConstraintNotSatisfied { constraint: Constraint { gate: Gate { index: 0, name: "constraint decompose" }, index: 0, name: "" }, row: 1, cell_values: [(VirtualCell { name: "", column: Column { column_type: Advice, index: 0 }, rotation: 0 }, "0x5"), (VirtualCell { name: "", column: Column { column_type: Advice, index: 0 }, rotation: 1 }, "0x5")] }])`,
 right: `Ok(())
```
while what would actually be helpful is something like:
```
error: constraint not satisfied
   Row    Advice
  Offset   0
     0   | a |    <-- { Gate "constraint decompose", constraint "foo"
     1   | b |        [ b + b * 0x100 + b * 0x10000 + b * 0x100_0000 - a = 0

  Assigned cell values:
      a = 0x5
      b = 0x5
```

**Comment by str4d** [comment]
https://rustc-dev-guide.rust-lang.org/diagnostics.html#error-messages documents how `rustc` builds its useful error reporting.

**Comment by str4d** [comment]
We probably wouldn't want anything nearly as fancy (to begin with), but here's the emitter for `rustc`: https://github.com/rust-lang/rust/blob/master/compiler/rustc_errors/src/emitter.rs

**Comment by daira** [comment]
Columns don't currently have names, do they? That might help a lot.

**Comment by str4d** [comment]
Indeed they don't. Same with lookup arguments. Once we've cut the`beta.2` for `zcashd 4.7.0` I'd like to make some of those breaking API changes to improve usability.

**Comment by daira** [comment]
And also it might help for queried cells used in constraints to have individual names.

**Comment by str4d** [comment]
Yeah, though that would be a much more painful breaking change if we were to alter the current API. It would be more reasonable to add a separate API that allows naming them if desired, and then tools like `MockProver::assert_satisfied` can use the variable names if set, and fill in local placeholders otherwise.
