### ISSUE TITLE
Add tests to ensure that EC fixed-base scalar mul supports full-width scalars

### ISSUE THREAD

**Issue by daira** [zcash/halo2#571]
It's somewhat complicated to ensure that all of the corner cases are covered, so I wanted to give that extra review and test cases. In particular, I want tests for cases that would fail if we didn't use complete addition for the last round. [Edit: it's a single round of complete addition for fixed-base; three rounds for variable-base.]

**Comment by therealyingtong** [comment]
This is done here:

https://github.com/zcash/halo2/blob/72ff677776504c288f4927a6ce8d3c273ebd588d/halo2_gadgets/src/ecc/chip/mul_fixed/full_width.rs#L206-L287
