### ISSUE TITLE
Prohibit queries of fixed columns at non-cur rotations.

### ISSUE THREAD

**Issue by ebfull** [zcash/halo2#585]
Rationale: There's [a technique](https://hackmd.io/@dJO3Nbl4RTirkR2uDM6eOA/BkoOdpwFF) that lets us make fixed columns almost free inside of recursion, which works ideally when fixed columns are not queried at non-cur rotations. I can't think of a situation where we would query a fixed column at an offset though? If we prohibited these queries entirely in the API, we could assume within recursion that we can deploy this trick.

**Comment by daira** [comment]
The only reason I can think of to allow querying a fixed column at a non-cur rotation, is to be able to combine (say) two fixed columns into one if you know that they are addressed disjointly by the same gate. For instance, suppose you have a custom gate that occupies two rows, and uses two fixed values, they could potentially be accessed from the same fixed column (one of the accesses using a "next" rotation).

I don't think that being able to do this rarely applicable (and manual) optimization is likely to outweigh the benefit for recursion.
