### ISSUE TITLE
Code isn't compiling for Original Xbox platform

### ISSUE THREAD

**Issue by ngrst183** [zcash/halo2#6]
Hi,

Have the latest XDK, tried compiling and it doesn't build, any help would be appreciated.

**Comment by daira** [comment]
I think this is maybe an upstream Microsoft issue :-p Were you able to get Rust working on this platform? I don't see it on their [supported platforms list](https://doc.rust-lang.org/nightly/rustc/platform-support.html) :-p

**Comment by ebfull** [comment]
Closing as WONTFIX, we're PC gamers. :smile:
