### ISSUE TITLE
ELI15: A question on vanish polynomial

### ISSUE THREAD

**Issue by smtmfft** [zcash/halo2#609]
## Which section of the Halo 2 book were you reading?
The vanish page
https://github.com/zcash/halo2/blob/745f5d159895bbff70d3086dcfec5ef46aba6981/book/src/design/proving-system/vanishing.md?plain=1#L50

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/99081233/175302885-d0836db4-6a9a-420a-b0d7-d632d96f87fd.png">

## What was unclear?
Should  $ X^{n(d-1)} h_{d-1}(X)$ be $X^{n(d-2)} h_{d-2}(X)$  If $d < n$ ?
As $n(d-1) > d(n-1) - n$, so that $h_{d-1}(X)$ could only be a constant 0 polynomial?
Thus I think the last $k = (d//n + 1)$ polynomials $h_{d-k}(X)$ are all 0 because h(X) is a $d(n-1) - n$ degree polynomial.

Correct me if I am wrong. Thanks!

**Comment by daira** [comment]
#427 will improve the implementation to use smaller extended domains when possible.

**Comment by smtmfft** [comment]
Got it, Thanks!
