### ISSUE TITLE
[MockProver] bug: `query_instance` always triggers `VerifyFailure::CellNotAssigned`.

### ISSUE THREAD

**Issue by therealyingtong** [zcash/halo2#621]
In the current `MockProver`, `query_instance` always results in a `VerifyFailure::CellNotAssigned` when used in a gate with a selector. This is because we only look for assigned cells in the region where the gate was activated, and instance cells are not in any region.

https://github.com/zcash/halo2/blob/96d9bde905a20117b4350ffba0b0a6479aa63f0a/halo2_proofs/src/dev.rs#L577-L593

**Comment by therealyingtong** [comment]
Thank you @nalinbhardwaj for surfacing this bug :bug:

**Comment by themighty1** [comment]
@str4d , is there a reason why https://github.com/zcash/halo2/pull/622 is still pending your review?
I'm finding this bug to slow down development, since I have to wait a long time to start up the real Prover every time I need to debug the circuit.
