### ISSUE TITLE
Document a working example of creating and verifying proofs in WASM

### ISSUE THREAD

**Issue by str4d** [zcash/halo2#630]
We definitely want WASM to be a viable target for `halo2_proofs`, but there is generally a lot of work required outside of the Rust code itself to make this work. We should add some documentation around how this can be achieved.

One of the 0xPARC participants made progress on WASM in their project: they have a working demo in the browser for a simple circuit, and have plans to create a template that can be used to bootstrap other projects. They also noted some blockers for having a full working example, such as needing a serialization formats for proving and verifying keys (#443 and #449). As this issue is the terminal case, any blockers will be opened as separate issues.

**Comment by zkbitcoin** [comment]
this does WASM proofs , got em all examples working (inc internal test case) very comprehensive , lacking just a semaphore circuit.. one thing I dosovered is problem on Safari but from tests I can tell it has to do with comlink library not halo2 itself

test suite does multithreading via google WASM implementation (wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon)

https://zkbitcoin.com/zk
