### ISSUE TITLE
Number of available rows is < 2^k

### ISSUE THREAD

**Issue by themighty1** [zcash/halo2#650]
My circuit's k == 7, which should give me 128 rows to work with.
I can use assign_fixed() to assign 122 rows. But as soon as I try to assign to the 123th row, I get an error:
`NotEnoughRowsAvailable { current_k: 7 }`

Is this the expected error? Is there a way to know in advance how many rows are reserved?

**Comment by daira** [comment]
Yes this is expected (some rows are reserved for zero knowledge blinding). Use `n - (cs.blinding_factors() + 1)`, where `cs` is the `ConstraintSystem`, to compute the number of available rows.
