### ISSUE TITLE
Generate PDF version of book

### ISSUE THREAD

**Issue by daira** [zcash/halo2#692]
This issue is inspired by a request by Michele Orrù in [his talk at ZKProof 5](https://www.youtube.com/watch?v=Mbz0v-Kiiq8&t=3195s): he wanted a way of generating PDF from mdbook source (his use case was for the Sigma Protocols specification of ZKProof, but the halo2 book was mentioned in the discussion).

**Comment by daira** [comment]
Based on the discussion at https://github.com/rust-lang/mdBook/issues/815, there appear to be two projects that try to tackle PDF output from mdbook: [mdbook-latex](https://crates.io/crates/mdbook-pdf) and [mdbook-pdf](https://crates.io/crates/mdbook-pdf).

I was able to get `mdbook-pdf` to work but it produces a PDF with severe rendering problems:
* Each section starts on a new page. This leads to huge stretches of blank space and many pages that only have a small amount of text at the stop; for me this completely breaks the flow when reading and defeats the point of rendering as PDF.
* Embedded LaTeX is not rendered (it appears as `$...$`). This is a showstopper.

`mdbook-latex` seems more promising since it converts to LaTeX and then to PDF, so should be able to handle embedded LaTeX correctly. I was not able to get it to work yet on Debian due to dependency issues (it depends on md2tex and Tectonic; just installing those via `pip` and the Tectonic installation instructions was not sufficient).

**Comment by HollowMan6** [comment]
Hi! I'm the creator of `mdbook-pdf`, here's the answers for your problems:
> - Each section starts on a new page. This leads to huge stretches of blank space and many pages that only have a small amount of text at the top; for me this completely breaks the flow when reading and defeats the point of rendering as PDF.

Actually this is a default behaviour of mdbook, you can turn it off by setting `page-break = false`: https://rust-lang.github.io/mdBook/format/configuration/renderers.html#outputhtmlprint

> - Embedded LaTeX is not rendered (it appears as $...$). This is a showstopper.

This is not an issue of mdbook-pdf. Your book.toml is misconfigured for mdbook-katex renderer. I have submitted a PR for the correct one with instructions and sample generated pdf file, enjoy!

#713

Thanks for choosing mdbook-pdf!
