### ISSUE TITLE
The code implementation does not match the description

### ISSUE THREAD

**Issue by simplelins** [zcash/halo2#780]

**Comment by daira** [comment]
There are many ways in which the code might not match the description; can you give more information? Is there any mismatch intended to be covered by this issue that is not fixed by #777?

**Comment by simplelins** [comment]
> There are many ways in which the code might not match the description; can you give more information? Is there any mismatch intended to be covered by this issue that is not fixed by #777?

this is a mistake, I failed to close this issue.
